<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'nama_produks' => 'Garang Gesing Panna Cotta',
                'kode_produks' => 'GGPC',
                'kategori_produks' => 1,
                'harga_produks' => 33000,
                'stok_produks' => 100,
                'deskripsi_produks' => 'Layered Caranggesing and rich coconut panna cota, crumble',
                'gambar_produks' => '1.jpg',
            ],
            [
                'nama_produks' => 'Au Lait Italian Tiramisu',
                'kode_produks' => 'AIT',
                'kategori_produks' => 1,
                'harga_produks' => 40000,
                'stok_produks' => 80,
                'deskripsi_produks' => 'Poured Tiramisu with mascarpone cheese, fresh milk',
                'gambar_produks' => '2.jpg',
            ],
            [
                'nama_produks' => 'Truffle Churros',
                'kode_produks' => 'TC',
                'kategori_produks' => 1,
                'harga_produks' => 39000,
                'stok_produks' => 90,
                'deskripsi_produks' => 'Truffle Churros served with crumble and vanilla ice cream',
                'gambar_produks' => '3.jpg',
            ],
            [
                'nama_produks' => 'Creme Brulle',
                'kode_produks' => 'CB',
                'kategori_produks' => 1,
                'harga_produks' => 33000,
                'stok_produks' => 95,
                'deskripsi_produks' => 'Classic Creme Brulle with fresh fruit',
                'gambar_produks' => '4.jpg',
            ],
            [
                'nama_produks' => 'Banana Waffle Nutella',
                'kode_produks' => 'BWN',
                'kategori_produks' => 1,
                'harga_produks' => 42000,
                'stok_produks' => 85,
                'deskripsi_produks' => 'Belgian sweet waffle, Nutella caramelized banana, caramel crumble, and ice cream',
                'gambar_produks' => '5.jpg',
            ],
            [
                'nama_produks' => 'Chocolate Fondant',
                'kode_produks' => 'CF',
                'kategori_produks' => 1,
                'harga_produks' => 35000,
                'stok_produks' => 88,
                'deskripsi_produks' => 'Choco lava cake with caramel crumble, fresh fruit, and ice cream',
                'gambar_produks' => '6.jpg',
            ],
            [
                'nama_produks' => 'Banana Epe',
                'kode_produks' => 'BE',
                'kategori_produks' => 1, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 37000,
                'stok_produks' => 92,
                'deskripsi_produks' => 'Grilled banana with jackfruit',
                'gambar_produks' => '7.jpg',
            ],
            [
                'nama_produks' => 'Banana Split',
                'kode_produks' => 'BS',
                'kategori_produks' => 1,
                'harga_produks' => 41000,
                'stok_produks' => 87,
                'deskripsi_produks' => 'Fresh honey banana with ice cream cookies',
                'gambar_produks' => '8.jpg',
            ],
            [
                'nama_produks' => 'Moccaffogato',
                'kode_produks' => 'MG',
                'kategori_produks' => 1, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 38000,
                'stok_produks' => 94,
                'deskripsi_produks' => 'Espresso mix choco with ice cream, granola, and cookies',
                'gambar_produks' => '9.jpg',
            ],
            [
                'nama_produks' => 'Panacotta',
                'kode_produks' => 'PC',
                'kategori_produks' => 1,
                'harga_produks' => 36000,
                'stok_produks' => 89,
                'deskripsi_produks' => 'Vanilla panna cotta with strawberry sauce',
                'gambar_produks' => '10.jpg',
            ],
            [
                'nama_produks' => 'Hollymoon Kiss',
                'kode_produks' => 'HK',
                'kategori_produks' => 1 ,
                'harga_produks' => 35000,
                'stok_produks' => 93,
                'deskripsi_produks' => 'Strawberry jam with ice cream and kiwi slice',
                'gambar_produks' => '11.jpg',
            ],
            [
                'nama_produks' => 'Sacher Cake',
                'kode_produks' => 'SC',
                'kategori_produks' => 1, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 43000,
                'stok_produks' => 91,
                'deskripsi_produks' => 'Chocolate cake topped with very rich dark chocolate',
                'gambar_produks' => '12.jpg',
            ],


            [
                'nama_produks' => 'Peanutbutter Oat Choco',
                'kode_produks' => 'POC',
                'kategori_produks' => 2, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 31000,
                'stok_produks' => 98,
                'deskripsi_produks' => 'Peanut sauce mix oatmilk and chocolate',
                'gambar_produks' => '13.jpg',
            ],
            [
                'nama_produks' => 'Pinacolada',
                'kode_produks' => 'PC',
                'kategori_produks' => 2,
                'harga_produks' => 40000,
                'stok_produks' => 85,
                'deskripsi_produks' => 'Pineapple and coconut water blend',
                'gambar_produks' => '14.jpg',
            ],
            [
                'nama_produks' => 'Sweet Cream Strawberry',
                'kode_produks' => 'SCS',
                'kategori_produks' => 2,
                'harga_produks' => 31000,
                'stok_produks' => 92,
                'deskripsi_produks' => 'Creamy strawberry Smoothies',
                'gambar_produks' => '15.jpg',
            ],
            [
                'nama_produks' => 'Sweet Melody',
                'kode_produks' => 'SM',
                'kategori_produks' => 2,
                'harga_produks' => 35000,
                'stok_produks' => 89,
                'deskripsi_produks' => 'Creamy coffee with apple and cinnamon flavour',
                'gambar_produks' => '16.jpg',
            ],
            [
                'nama_produks' => 'Pinacoco',
                'kode_produks' => 'PCO',
                'kategori_produks' => 2,
                'harga_produks' => 32000,
                'stok_produks' => 94,
                'deskripsi_produks' => 'Mix coconut pineapple juice and lemon',
                'gambar_produks' => '17.jpg',
            ],
            [
                'nama_produks' => 'Snow Blue',
                'kode_produks' => 'SB',
                'kategori_produks' => 2,
                'harga_produks' => 39000,
                'stok_produks' => 87,
                'deskripsi_produks' => 'Creamy sweet and sour',
                'gambar_produks' => '18.jpg',
            ],
            [
                'nama_produks' => 'Green Canyon',
                'kode_produks' => 'GC',
                'kategori_produks' => 2,
                'harga_produks' => 35000,
                'stok_produks' => 91,
                'deskripsi_produks' => 'Fresh vegetable with pineapple juice',
                'gambar_produks' => '19.jpg',
            ],
            [
                'nama_produks' => 'Brew Gimont',
                'kode_produks' => 'BG',
                'kategori_produks' => 2, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 35000,
                'stok_produks' => 88,
                'deskripsi_produks' => 'Mix cold brew, Ginger flavour and lemon juice',
                'gambar_produks' => '20.jpg',
            ],
            [
                'nama_produks' => 'Coconut Mojito',
                'kode_produks' => 'CM',
                'kategori_produks' => 2,
                'harga_produks' => 32000,
                'stok_produks' => 90,
                'deskripsi_produks' => 'Sparkling coconut water and mint',
                'gambar_produks' => '21.jpg',
            ],
            [
                'nama_produks' => 'Tropical Honey Fruit',
                'kode_produks' => 'THF',
                'kategori_produks' => 2,
                'harga_produks' => 37000,
                'stok_produks' => 93,
                'deskripsi_produks' => 'Fresh sweet fruit and tropical fruit',
                'gambar_produks' => '22.jpg',
            ],
            [
                'nama_produks' => 'Tropical Fresh Fruit Bowl',
                'kode_produks' => 'TFFB',
                'kategori_produks' => 2,
                'harga_produks' => 33000,
                'stok_produks' => 95,
                'deskripsi_produks' => 'Fresh sour with coconut water, and tropical fruit',
                'gambar_produks' => '23.jpg',
            ],
            [
                'nama_produks' => 'Avocado Honey Bowl',
                'kode_produks' => 'AHB',
                'kategori_produks' => 2,
                'harga_produks' => 33000,
                'stok_produks' => 97,
                'deskripsi_produks' => 'Avocado, Pineapple, Honey and Banana',
                'gambar_produks' => '24.jpg',
            ],

            [
                'nama_produks' => 'Chicken Cordon Bleu',
                'kode_produks' => 'CCB',
                'kategori_produks' => 3, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 75000,
                'stok_produks' => 85,
                'deskripsi_produks' => 'Classic chicken cordon blue served with lyonnese potato and mushroom',
                'gambar_produks' => '25.jpg',
            ],
            [
                'nama_produks' => 'Char Grilled Wagyu Maranggi',
                'kode_produks' => 'CGWM',
                'kategori_produks' => 3,
                'harga_produks' => 130000,
                'stok_produks' => 78,
                'deskripsi_produks' => 'Grilled beef wagyu maranggi and choice of side dish',
                'gambar_produks' => '26.jpg',
            ],
            [
                'nama_produks' => 'Beef Stroganof',
                'kode_produks' => 'BS',
                'kategori_produks' => 3,
                'harga_produks' => 98000,
                'stok_produks' => 90,
                'deskripsi_produks' => 'Slow-cooked beef in creamy sauce and mushroom served with choice of side dish',
                'gambar_produks' => '27.jpg',
            ],
            [
                'nama_produks' => 'Pan Seared Norwegian Salmon',
                'kode_produks' => 'PSNS',
                'kategori_produks' => 3,
                'harga_produks' => 115000,
                'stok_produks' => 82,
                'deskripsi_produks' => 'Grill Norwegian salmon with garlic lemon butter sauce and choice of side dish',
                'gambar_produks' => '28.jpg',
            ],
            [
                'nama_produks' => 'Salmon Mentai',
                'kode_produks' => 'SM',
                'kategori_produks' => 3,
                'harga_produks' => 85000,
                'stok_produks' => 95,
                'deskripsi_produks' => 'Grilled salmon serve with fragrant jasmine rice, mentai sauce, scramble egg, and seaweed',
                'gambar_produks' => '29.jpg',
            ],
            [
                'nama_produks' => 'Pad Thai Seafood',
                'kode_produks' => 'PTS',
                'kategori_produks' => 3, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 89000,
                'stok_produks' => 88,
                'deskripsi_produks' => 'Pad Thai with seafood, veggies, chili flake, and crackers',
                'gambar_produks' => '30.jpg',
            ],
            [
                'nama_produks' => 'Chicken Hainan Char Siu',
                'kode_produks' => 'CHCS',
                'kategori_produks' => 3,
                'harga_produks' => 74000,
                'stok_produks' => 93,
                'deskripsi_produks' => 'Chinese BBQ Chicken, Hainan rice, and Hainan Broth',
                'gambar_produks' => '31.jpg',
            ],
            [
                'nama_produks' => 'Wagyu Beef Fried Rice',
                'kode_produks' => 'WBFR',
                'kategori_produks' => 3,
                'harga_produks' => 76000,
                'stok_produks' => 87,
                'deskripsi_produks' => 'Ejo fried rice with wagyu, acar, and crackers',
                'gambar_produks' => '32.jpg',
            ],
            [
                'nama_produks' => 'Striploin Angus',
                'kode_produks' => 'SA',
                'kategori_produks' => 3, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 125000,
                'stok_produks' => 91,
                'deskripsi_produks' => 'Served with mash potato, sauced spinach, and chickpeas',
                'gambar_produks' => '33.jpg',
            ],
            [
                'nama_produks' => 'Meat and Prawn',
                'kode_produks' => 'MAP',
                'kategori_produks' => 3,
                'harga_produks' => 158000,
                'stok_produks' => 94,
                'deskripsi_produks' => 'Grill us top blade, grill prawn, potato mozzarella braised short plate, and pepper sauce',
                'gambar_produks' => '34.jpg',
            ],
            [
                'nama_produks' => 'Aglio Salmon Belly',
                'kode_produks' => 'ASB',
                'kategori_produks' => 3,
                'harga_produks' => 98000,
                'stok_produks' => 92,
                'deskripsi_produks' => 'Spicy pasta with salmon belly and kemangi tuile',
                'gambar_produks' => '35.jpg',
            ],
            [
                'nama_produks' => 'Australian Healty Brunch',
                'kode_produks' => 'AHB',
                'kategori_produks' => 3,
                'harga_produks' => 88000,
                'stok_produks' => 96,
                'deskripsi_produks' => 'Vegetable and scramble egg, served with chickpea, slice avocado, brown, and sautéed mushroom',
                'gambar_produks' => '36.jpg',
            ],

            [
                'nama_produks' => 'Onion Rings',
                'kode_produks' => 'OR',
                'kategori_produks' => 4, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 25000,
                'stok_produks' => 100,
                'deskripsi_produks' => 'Crispy onion rings with tartar sauce',
                'gambar_produks' => '37.jpg',
            ],
            [
                'nama_produks' => 'French Fries',
                'kode_produks' => 'FF',
                'kategori_produks' => 4,
                'harga_produks' => 22000,
                'stok_produks' => 98,
                'deskripsi_produks' => 'Original French fries',
                'gambar_produks' => '38.jpg',
            ],
            [
                'nama_produks' => 'Caramel Butter Crispy Banana',
                'kode_produks' => 'CBCB',
                'kategori_produks' => 4,
                'harga_produks' => 32000,
                'stok_produks' => 90,
                'deskripsi_produks' => 'Honey-buttered crispy banana, caramel sauce, and vanilla ice cream',
                'gambar_produks' => '39.jpg',
            ],
            [
                'nama_produks' => 'Crispy Salt and Pepper Tofu',
                'kode_produks' => 'CSPT',
                'kategori_produks' => 4,
                'harga_produks' => 22000,
                'stok_produks' => 96,
                'deskripsi_produks' => 'Crispy tofu with savory seasoning',
                'gambar_produks' => '40.jpg',
            ],
            [
                'nama_produks' => 'Savoury Cheese Cassava',
                'kode_produks' => 'SCC',
                'kategori_produks' => 4, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 30000,
                'stok_produks' => 92,
                'deskripsi_produks' => 'Tender fried cassava with cheese sauce',
                'gambar_produks' => '41.jpg',
            ],
            [
                'nama_produks' => 'Seafood Fritters of Twisted Dough',
                'kode_produks' => 'SFTD',
                'kategori_produks' => 4,
                'harga_produks' => 28000,
                'stok_produks' => 88,
                'deskripsi_produks' => 'Seafood twisted dough, creamy mayonnaise, sesame sauce, and katsuobushi',
                'gambar_produks' => '42.jpg',
            ],
            [
                'nama_produks' => 'Garlic Parmesan Chicken Wings',
                'kode_produks' => 'GPCW',
                'kategori_produks' => 4,
                'harga_produks' => 37000,
                'stok_produks' => 94,
                'deskripsi_produks' => 'Crispy chicken wings garlic parmesan',
                'gambar_produks' => '43.jpg',
            ],
            [
                'nama_produks' => 'Potato Wedges',
                'kode_produks' => 'PW',
                'kategori_produks' => 4, // Sesuaikan dengan id kategori yang sesuai
                'harga_produks' => 28000,
                'stok_produks' => 89,
                'deskripsi_produks' => '150g potato wedges in spicy seasoning and tartar sauce',
                'gambar_produks' => '44.jpg',
            ],
            [
                'nama_produks' => 'Mozzarella Stick',
                'kode_produks' => 'MS',
                'kategori_produks' => 4,
                'harga_produks' => 31000,
                'stok_produks' => 97,
                'deskripsi_produks' => 'Melted mozzarella with in and out sauce',
                'gambar_produks' => '45.jpg',
            ],
            [
                'nama_produks' => 'Calamari Rings',
                'kode_produks' => 'CR',
                'kategori_produks' => 4,
                'harga_produks' => 29000,
                'stok_produks' => 93,
                'deskripsi_produks' => 'Crispy calamari rings with tartar sauce',
                'gambar_produks' => '46.jpg',
            ],
            [
                'nama_produks' => 'Fish and Chips',
                'kode_produks' => 'FC',
                'kategori_produks' => 4,
                'harga_produks' => 40000,
                'stok_produks' => 91,
                'deskripsi_produks' => 'Crispy fried fish, fries, and tartar sauce',
                'gambar_produks' => '47.jpg',
            ],
            [
                'nama_produks' => 'Honey Chicken Wings',
                'kode_produks' => 'HCW',
                'kategori_produks' => 4,
                'harga_produks' => 37000,
                'stok_produks' => 95,
                'deskripsi_produks' => 'Crispy chicken wings honey BBQ with bell pepper aioli sauce',
                'gambar_produks' => '48.jpg',
            ],
        ];

        DB::table('tbl_produks')->insert($data);
    }
}
